apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:latest
          name: grafana
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: admin
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: grafana-persistent-storage
              mountPath: /var
            - name: grafana-ini-configmap-volume
              mountPath: /etc/grafana
            - name: grafana-dashboard-directory-configmap-volume
              mountPath: /var/lib/grafana/provisioning/dashboards
            - name: grafana-dashboard-json-configmap-volume
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-datasource-configmap-volume
              mountPath: /var/lib/grafana/provisioning/datasources
      volumes:
        - name: grafana-ini-configmap-volume
          configMap:
            defaultMode: 0666
            name: grafana-ini
        - name: grafana-dashboard-directory-configmap-volume
          configMap:
            defaultMode: 0666
            name: grafana-dashboard-directory
        - name: grafana-dashboard-json-configmap-volume
          configMap:
            defaultMode: 0666
            name: grafana-dashboard-json
        - name: grafana-datasource-configmap-volume
          configMap:
            defaultMode: 0666
            name: grafana-datasource
        - name: grafana-persistent-storage
          emptyDir: {}
