apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector: 
    app: prometheus
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090 
      nodePort: 30000
